### ISSUE TITLE
Allow bento package to create a .bento file

### ISSUE THREAD

**Issue by mattgi** [bentojs/cli#5]
If a user wishes to run the api locally from within the same folder that they are making edits, the `.bento` will be updated locally. We do not want this as we want `bento package` to be run on CI and servers and the contents to be created based on what is present in node_modules and project folders.

As such, we should not commit a .bento file in to a repository and should instead have bento just generate the file if it does not yet exist. `.bento` should be present in the .gitignore.

**Comment by mattgi** [comment]
I should add that the above all works fine.. it is just that it is currently not possible to delete the .bento file (to remove it from the repo) as the cli depends on it existing at present.

**Comment by mattgi** [comment]
On rethinking my above comment, it wont work if I just remove the file from the repo.. as CI will fail (as bento package depends on the file existing).. so it needs to be fixed in the cli before its removed.

**Comment by Kodemon** [comment]
The `.bento` file has to be present as it defines the `platform` the cli should take into consideration for each operation. `package` on web is not the same as in api etc.

When you run `bento package` it will always run through the `node_module`, `modules`, and `providers` folder to setup the required paths etc. It will over-write the old paths each time `bento package` is executed.

**Comment by mattgi** [comment]
Hmmk. The issue currently is that you must commit `.bento` to the repo as it is required for `bento package` to execute. So I guess we just commit it every time there is a change, but this means every pull could require you to run `bento package` to "recreate/refresh" `.bento`.

The reasoning behind this request is for the (majority of) people who git clone a library, run npm install, bento package, and then npm run local. i.e. running it in place. Based on the current flow, it means that the .bento package needs to committed every time a user touches that file by funning bento package. In theory this should not matter as every user should have the same .bento file locally but it seems like an anti-pattern to require the file to exist, only so that it can be re-written. I'm wondering if the folder name could be used to infer the project type (i.e. /api, /web, etc.).

**Comment by Kodemon** [comment]
Yeah, the changes would be overwritten if you keep changing the file. That means if you are not running bento off a secondary server you would have the modified file in a polluted repository.

The only viable solution to this is having `bento package` generating its own `.packages` files that is appended to the settings generation in the core (much like config).

**Comment by Kodemon** [comment]
Make sure to update bentojs api to 1.3.3 or above for these changes to take effect.
